## NUMPY 

* Numpy Initialization
* creating ndarrays in NumPy
* Multi-dimesnional Arrays
* Sorting array 
* Broadcasting

# Numpy introduction 
Numerik Python digunakan luas di Pandas, SciPy, Matplotlib, dll 


In [494]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\eliza\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [495]:
import numpy as np 
np.__version__

'1.23.2'

In [496]:
## Adding Vector dengan menggunakan pure python without numpy 
def pythonsum(n): 
    a = b = list(range(n)) ## range returns a lazy sequence object - it does not return a list 
    c = [] #output 
    for i in range (len(a)):
        x = a[i] ** 2
        y = b[i] ** 2
        c.append(x+y)
        return c
    c = pythonsum(10)
    print(c)

In [497]:
def numpytsum(n): 
    a = np.arrange(n) ** 2
    b = np.arrange(n) ** 3

## ini belum selesai codingannya 

In [498]:
## membandingkan kecepatan numpy dg list core python 
from datetime import datetime
size = 100 
start = datetime.now()
c = pythonsum(size)
delta = datetime.now() - start

## ini belum selesai codingannya

## Array 
array merup struktur data pusat dari library NumPy. Bentuk array adalah tuple bilangan bulat yag memberikan ukuran array di sepanjang dimensi  
a = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])

print(a[0])  ## ini mengambil kurung siku yang paling kiri 

keluaran: 
[1 2 3 4]

array 1D, array 2D, 

Kelas NumPy ndarray digunakan untuk mewakili ..... 

In [499]:
## Numpy Initialisation
from numpy import *

In [500]:
array([1,2,3])

array([1, 2, 3])

In [501]:
import numpy

In [502]:
numpy.array([1,2,3])

array([1, 2, 3])

In [503]:
import numpy as np 
np.array([1,2,3])

array([1, 2, 3])

In [504]:
array1 = np.arange(100)

In [505]:
np.set_printoptions(threshold=10) ##sys.maxise

In [506]:
array2 = list(range(100))

In [507]:
print(array1)

[ 0  1  2 ... 97 98 99]


In [508]:
print(array2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [509]:
## membuat list 
my_list = list(range(5))
my_list
print(type(my_list))

<class 'list'>


In [510]:
## you can create an array with a range of elements 
print(np.arange(4)) #start default = 0, stop = 4, step default = 1
print(np.arange(1,10)) #start, stop, step default = 1
print(np.arange(2, 10, 2)) #start 0, stop = 10 step = 2


[0 1 2 3]
[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


## Add, Remove dan Sort

In [511]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [512]:
arr = np.append(arr, [9,10])
print(arr)

[ 1  2  3  4  5  6  7  9 10]


In [513]:
#menghapus index 1
np.delete(arr, 1)

array([ 1,  3,  4,  5,  6,  7,  9, 10])

In [514]:
arrsort = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [515]:
data = np.sort(arrsort)
print(data)

[1 2 3 4 5 6 7 8]


## Multi - Dimensional Arrays 

In [516]:
import numpy as np 
multi_list =[[0,1,2,3,], [10,11,12,13]]
print((type(multi_list)))
multi_list

<class 'list'>


[[0, 1, 2, 3], [10, 11, 12, 13]]

In [517]:
a = np. array(multi_list)
print(type(a))
print(a.ndim)
a.shape

<class 'numpy.ndarray'>
2


(2, 4)

## ndim, shape and Size 

In [518]:
## bagian ini ketinggalan coba cek lagi 

## Sorting Aray 
np.sort signature: np.sort(a, axis = -1, kind = None)

In [519]:
data = np.array([[4,1,0,5],[1,5,3,4]])
data


array([[4, 1, 0, 5],
       [1, 5, 3, 4]])

In [520]:
## menambahkan paramete axis = 0
data = np.array([[4,1,0,5],[1,5,3,4]])
print(data)
print("sebelum di sort axis =0 ")
print(10*"====")
data.sort(axis=0)

[[4 1 0 5]
 [1 5 3 4]]
sebelum di sort axis =0 


In [521]:
## sorting dengan membuat structure array 
dtype= [('name', 'S10'), ('height', float), ('age', int)] ##name type string, height type float 
dtype

[('name', 'S10'), ('height', float), ('age', int)]

In [522]:
values = [('Arthur', 1.8, 41),
        ('Lancelot', 1.9, 38),
        ('Galahad', 1.7, 38)]
values

[('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [523]:
a = np.array(values, dtype=dtype) ## create a structures array 
print(a)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [524]:
x = np.sort(a, order='name')
print(x)

[(b'Arthur', 1.8, 41) (b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38)]


In [525]:
np.sort(a, order = ['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [526]:
values[1] #menghasilkan tuple

('Lancelot', 1.9, 38)

In [527]:
values[0][0] ##Arthur

'Arthur'

In [528]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [529]:
dzero = np. zeros((2,2,2))
print(dzero)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [530]:
dzero.shape

(2, 2, 2)

In [531]:
dzero.ndim

3

## Reshape 
np.reshape() bentuk baru array tanpa ubah data 
misal 12 element: 4x3, 3x4, 12x1 

numpy.reshape(a,newshape,order)

order : 'C' berarti membaca/menulis elemen dengan urutan indeks spt C
dll 

In [532]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [533]:
a = np.arange(6). reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [534]:
np.reshape(a, (2,3))

array([[0, 1, 2],
       [3, 4, 5]])

## Creating Array from Existing Data

* Slicing indexing 
* np.vstack()
* np.hstack()
* np.hsplit()
* .view()
* .copy()
membuat array baru dari bagian array Anda kapan saja dengan menentukan di mana Anda ingin mengiri array Anda. 

In [535]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

## Matrix Aggregation
dapat menjumlahkan matrix dengan cara yang sama seperti kita menjumlahkan vektor

In [536]:
data = np.array([[1,2], [3,4], [5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [537]:
print(data.max())
print(data)

6
[[1 2]
 [3 4]
 [5 6]]


In [538]:
#membuat salinan 
c = a.copy()

## Copying 

In [539]:
x = [0,1]
y = [9,8]
z = x

print(x)
z[0] = 5
print(x)

[0, 1]
[5, 1]


In [540]:
p = y.copy()

## Addition,

In [541]:
a = np.array([1, 2, 3, 4])

#menambahkan semua elemen dalam array 
a.sum()

10

In [542]:
b = np.array([[1,1], [2,2]])
print(b)


[[1 1]
 [2 2]]


In [543]:
# anda dapat menjumlahkan baris 
b.sum(axis = 0)

array([3, 3])

In [544]:
b.sum(axis=1)

array([2, 4])

In [545]:
data = np.array([1,2])


In [546]:
ones=np.ones(2)

In [547]:
data + ones

array([2., 3.])

## More Array Operations
maximum, minimum, sum, dll. 

## Matrix Arithmetic 

In [550]:
np.dot(3,4)

12

In [552]:
np_m =np.arange(1,17)
np_m

array([ 1,  2,  3, ..., 14, 15, 16])